server:
  port: 8081
spring:
  application:
    name: "driveradaptermyslq"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "jdbc:mysql://localhost:3306/clean_architecture_db"
    username: "root"
    password: "password"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    databasePlatform: "org.hibernate.dialect.MySQL5Dialect"
  jwt:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 7200000 # two hours
# four hours 14400000

